### ISSUE TITLE
Overlap check fails for dhcp interface

### ISSUE THREAD

**Issue by JoshuaLyle** [opoplawski/ansible-pfsense#36]
Interfaces that have been setup for DHCP and/or do not have an address yet fail `_check_overlaps` when trying to setup an interface because it expects to have a valid IP address but the "address" it receives is `u'dhcp/None'`

My temporary fix was to comment out the overlap check.

```
Traceback (most recent call last):
  File \"/root/.ansible/tmp/ansible-tmp-1578515006.8685193-152090955772829/AnsiballZ_pfsense_interface.py\", line 102, in <module>
    _ansiballz_main()
  File \"/root/.ansible/tmp/ansible-tmp-1578515006.8685193-152090955772829/AnsiballZ_pfsense_interface.py\", line 94, in _ansiballz_main    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/root/.ansible/tmp/ansible-tmp-1578515006.8685193-152090955772829/AnsiballZ_pfsense_interface.py\", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.pfsense_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File \"/usr/local/lib/python2.7/runpy.py\", line 188, in run_module
    fname, loader, pkg_name)
  File \"/usr/local/lib/python2.7/runpy.py\", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File \"/usr/local/lib/python2.7/runpy.py\", line 72, in _run_code
    exec code in run_globals
  File \"/tmp/ansible_pfsense_interface_payload_AadC14/ansible_pfsense_interface_payload.zip/ansible/modules/pfsense_interface.py\", line 137, in <module>
  File \"/tmp/ansible_pfsense_interface_payload_AadC14/ansible_pfsense_interface_payload.zip/ansible/modules/pfsense_interface.py\", line 132, in main
  File \"/tmp/ansible_pfsense_interface_payload_AadC14/ansible_pfsense_interface_payload.zip/ansible/module_utils/network/pfsense/pfsense_module_base.py\", line 182, in run
  File \"/tmp/ansible_pfsense_interface_payload_AadC14/ansible_pfsense_interface_payload.zip/ansible/module_utils/network/pfsense/pfsense_interface.py\", line 114, in _params_to_obj
  File \"/tmp/ansible_pfsense_interface_payload_AadC14/ansible_pfsense_interface_payload.zip/ansible/module_utils/network/pfsense/pfsense_interface.py\", line 73, in _check_overlaps
  File \"/tmp/ansible_pfsense_interface_payload_AadC14/ansible_pfsense_interface_payload.zip/ansible/module_utils/compat/ipaddress.py\", line 261, in ip_network
ValueError: u'dhcp/None' does not appear to be an IPv4 or IPv6 network
```

**Comment by f-bor** [comment]
Sorry about that. It's fixed.

**Comment by JoshuaLyle** [comment]
thanks for the quick fix! really cool project y'all have here!

**Comment by f-bor** [comment]
Thanks ! And cool users :)

**Comment by JoshuaLyle** [comment]
```
The full traceback is:
Traceback (most recent call last):                                                                                  
  File "/root/.ansible/tmp/ansible-tmp-1578521539.0594368-85925942926677/AnsiballZ_pfsense_interface.py", line 102, in <module>
    _ansiballz_main() 
  File "/root/.ansible/tmp/ansible-tmp-1578521539.0594368-85925942926677/AnsiballZ_pfsense_interface.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1578521539.0594368-85925942926677/AnsiballZ_pfsense_interface.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.pfsense_interface', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_pfsense_interface_payload_tV3fl2/ansible_pfsense_interface_payload.zip/ansible/modules/pfsense_interface.py", line 137, in <module>
  File "/tmp/ansible_pfsense_interface_payload_tV3fl2/ansible_pfsense_interface_payload.zip/ansible/modules/pfsense_interface.py", line 132, in main
  File "/tmp/ansible_pfsense_interface_payload_tV3fl2/ansible_pfsense_interface_payload.zip/ansible/module_utils/network/pfsense/pfsense_module_base.py", line 182, in run
  File "/tmp/ansible_pfsense_interface_payload_tV3fl2/ansible_pfsense_interface_payload.zip/ansible/module_utils/network/pfsense/pfsense_interface.py", line 114, in _params_to_obj
  File "/tmp/ansible_pfsense_interface_payload_tV3fl2/ansible_pfsense_interface_payload.zip/ansible/module_utils/network/pfsense/pfsense_interface.py", line 73, in _check_overlaps
  File "/tmp/ansible_pfsense_interface_payload_tV3fl2/ansible_pfsense_interface_payload.zip/ansible/module_utils/compat/ipaddress.py", line 261, in ip_network
ValueError: u'dhcp/None' does not appear to be an IPv4 or IPv6 network
```

Hmmm so it seems it's still happening. I'm not sure where it's getting `u'dhcp/None` from. To give more info about my use case, I have a VM with 3 interfaces with the WAN set to DHCP. I use the `pfsense_interface` module to iterate over the other 2 interfaces, `vtnet1` and `vtnet2`, to set their IPs to a static `10.0.1.1` and `10.0.2.1` respectively.

**Comment by f-bor** [comment]
I got it wrong. It's fixed (for good now).

**Comment by JoshuaLyle** [comment]
just tested it on a fresh machine and it looks like it's working. Thanks again!
