### ISSUE TITLE
pfsense_nat_port_forward fails with example

### ISSUE THREAD

**Issue by JoshuaLyle** [opoplawski/ansible-pfsense#37]
pfsense nat port forward fails with [the example given in the module's doc](https://github.com/opoplawski/ansible-pfsense/wiki/pfsense_nat_port_forward) below as well as with parameters that fit my environment (changing the ports to `80` and the target to `10.0.0.50:80`).

```
  - name: "Add NAT port forward traffic rule"
    pfsense_nat_port_forward:
      descr: 'ssh'
      interface: wan
      source: any
      destination: any:22
      target: 1.2.3.4:22
      associated_rule: pass
      state: present
```

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1578519901.9509819-67012684930639/AnsiballZ_pfsense_nat_port_forward.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1578519901.9509819-67012684930639/AnsiballZ_pfsense_nat_port_forward.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1578519901.9509819-67012684930639/AnsiballZ_pfsense_nat_port_forward.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.pfsense_nat_port_forward', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_pfsense_nat_port_forward_payload_nR4yGm/ansible_pfsense_nat_port_forward_payload.zip/ansible/modules/pfsense_nat_port_forward.py", line 137, in <module>
  File "/tmp/ansible_pfsense_nat_port_forward_payload_nR4yGm/ansible_pfsense_nat_port_forward_payload.zip/ansible/modules/pfsense_nat_port_forward.py", line 132, in main
  File "/tmp/ansible_pfsense_nat_port_forward_payload_nR4yGm/ansible_pfsense_nat_port_forward_payload.zip/ansible/module_utils/network/pfsense/pfsense_module_base.py", line 184, in run
  File "/tmp/ansible_pfsense_nat_port_forward_payload_nR4yGm/ansible_pfsense_nat_port_forward_payload.zip/ansible/module_utils/network/pfsense/pfsense_nat_port_forward.py", line 210, in _find_target
TypeError: 'NoneType' object is not iterable
```

**Comment by f-bor** [comment]
Thanks for reporting. It's fixed.

**Comment by JoshuaLyle** [comment]
haven't had any further problems. Thank you!
